routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|Route::get('login','LoginController@login')->name('login-view');
 */

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', 'LoginController@login')->name('login-view');
Route::post('login', 'LoginController@authenticate')->name('post-login');
Route::get('forgot-password', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.email');
Route::post('forgot-password', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

Route::get('reset-password/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('reset-pasword', 'Auth\ResetPasswordController@reset')->name('password.reset');

Route::get('home', 'LoginController@home')->name('home-view');
Route::get('signup', 'RegisterAccountController@signup')->name('signup');
Route::get('users', 'SignUpController@users');
Route::post('createUsers', 'RegisterAccountController@createaccount')->name('create-user');
// Route::post('createaccount','RegisterAccountController@createaccount')->name('create-account');
Route::group(['prefix' => 'onboarding', 'as' => 'onboarding.', 'middleware' => 'auth'], function () {
    Route::post('farmsetup', ['as' => 'farmsetup', 'uses' => 'FarmAccountController@createOrUpdateFarmAccount']);
    Route::post('penhouse', ['as' => 'penhouse', 'uses' => 'PenHouseController@createPenHouse']);
    Route::post('penhouseupdate', ['as' => 'penhouseupdate', 'uses' => 'PenHouseController@UpdatePenHouse']);
    Route::post('penhouse/delete', ['as' => 'penhousedelete', 'uses' => 'PenHouseController@deletePenHouse']);

    Route::post('stocking', ['as' => 'stocking', 'uses' => 'PenHouseStockingController@createOrUpdateStocking']);
    Route::post('stocking/delete/{id}', ['as' => 'updatestocking', 'uses' => 'PenHouseStockingController@updatePenHouseStocking']);
    Route::delete('stocking/delete/{id}', ['as' => 'deletestocking', 'uses' => 'PenHouseStockingController@deletePenhouseStocking']);

    Route::post('stockingupdate', ['as' => 'stockingupdate', 'uses' => 'PenHouseStockingController@editStocking']);

    Route::get('farmsetup', ['as' => 'farmsetup', 'uses' => 'FarmAccountController@farmSetUpView']);
    Route::get('penhouse', ['as' => 'penhouse', 'uses' => 'PenHouseController@penHouseView']);
    // Route::get('penhouse/{id?}', ['as' => 'penhouse', 'uses' => 'PenHouseController@penHouseViewUpdate']);
    Route::get('stocking', ['as' => 'stocking', 'uses' => 'PenHouseStockingController@penHouseStockingView']);

});

//Route::match(['get', 'put'], 'update/{id}', 'Crud5Controller@update');
Route::group(['prefix' => 'birds', 'as' => 'birds.', 'middleware' => 'auth'], function () {
    Route::get('penhouses', ['as' => 'penhouses', 'uses' => 'PenHouseController@dashPenHouseView']);
    Route::post('penhouses', ['as' => 'penhouses', 'uses' => 'PenHouseController@createDashPenHouse']);
    Route::get('stock', ['as' => 'stock', 'uses' => 'PenHouseStockingController@dashPenHouseStockingView']);
    Route::post('stocking', ['as' => 'stocking', 'uses' => 'PenHouseStockingController@createOrUpdateDashStocking']);
    Route::put('stocking/{id}', ['as' => 'updatestocking', 'uses' => 'PenHouseStockingController@updateDashStocking']);
    Route::get('cyclelist', ['as' => 'stocktracking', 'uses' => 'StockingTrackingController@stockTrackingView']);
    
    Route::get('mortality', ['as' => 'mortality', 'uses' => 'CullingDeadBirdsController@deadBirdsView']);
   
    Route::put('mortality/update/{id}', ['as' => 'updatemortality', 'uses' => 'CullingDeadBirdsController@deadBirdsUpdate']);
   
    Route::delete('mortality/delete/{id}', ['as' => 'deletemortality', 'uses' => 'CullingDeadBirdsController@deadBirdsDelete']);
   
    Route::post('mortality', ['as' => 'mortality', 'uses' => 'CullingDeadBirdsController@deadBirdsCreate']);
    
    Route::get('feedgiven', ['as' => 'feedgiven', 'uses' => 'FeedRecordController@feedRecordingView']);
    Route::post('givefeed', ['as' => 'recordfeed', 'uses' => 'FeedRecordController@createFeedRecording']);
    Route::put('givefeed/update/{id}', ['as' => 'updaterecordfeed', 'uses' => 'FeedRecordController@updateFeedRecording']);
    Route::delete('givefeed/delete/{id}', ['as' => 'deleterecordfeed', 'uses' => 'FeedRecordController@deleteFeedRecording']);
    
    Route::get('drugtaking', ['as' => 'druggiven', 'uses' => 'FarmDrugRecordingController@createDrugRecording']);
   
    Route::post('givedrug', ['as' => 'recorddrug', 'uses' => 'FarmDrugRecordingController@createDrugRecording']);
    Route::put('givedrug/update/{id}', ['as' => 'updatedrugrecord', 'uses' => 'FarmDrugRecordingController@updateFarmDrugRecording']);
    Route::delete('givedrug/delete/{id}', ['as' => 'deletedrugrecord', 'uses' => 'FarmDrugRecordingController@deleteFarmDrugRecording']);
    Route::get('feedwastage', ['as' => 'feedwastage', 'uses' => 'FarmWastageController@createWasteRecording']);
    Route::post('feedwastage', ['as' => 'feedwastage', 'uses' => 'FarmWastageController@createWasteRecording']);
    Route::put('feedwastage/update/{id}', ['as' => 'updatefeedwastage', 'uses' => 'FarmWastageController@updateWasteRecording']);
    Route::delete('feedwastage/delete/{id}', ['as' => 'deletefeedwastage', 'uses' => 'FarmWastageController@deleteWasteRecording']);

///DELETE MORTALITES

Route::post('/editCullingDeadBirds', ['as' => 'editCullingDeadBirds', 'uses' => 'CullingDeadBirdsController@editCullingDeadBirds']);
   

});

Route::get('vendor', ['as' => 'vendor', 'uses' => 'VendorController@rendorVendor']);
Route::post('vendor', ['as' => 'vendor', 'uses' => 'PenHouseStockingController@penHouseStockingView']);
Route::post('vendor/{id}', ['as' => 'vendor', 'uses' => 'PenHouseStockingController@penHouseStockingView']);

//account group routings

Route::group(['prefix' => 'account', 'as' => 'account.', 'middleware' => 'auth'], function () {

    Route::get('/farm-setup', ['as' => 'farmsetup', 'uses' => 'AccountController@farmsetup']);

    Route::get('/pen-house-creation', ['as' => 'penhouse', 'uses' => 'AccountController@penhouse']);

    Route::get('/stocking-setup', ['as' => 'stockingsetup', 'uses' => 'AccountController@stockingsetup']);

    //Check for the onboarding if done...

    Route::get('/dashboard', ['as' => 'index', 'uses' => 'AccountController@index'])->middleware('onboarding');;
    Route::get('settings', ['as' => 'settings', 'uses' => 'AccountController@index']);

    Route::get('registereggs', ['as' => 'forms', 'uses' => 'AccountController@forms']);

    Route::get('/billrecords', ['as' => 'viewbills', 'uses' => 'BillsController@viewBills']);
    Route::delete('/viewbilldetails/{id}', ['as' => 'deletebill', 'uses' => 'BillsController@deletebill']);

    Route::get('/viewbilldetails/{id}', ['as' => 'viewbilldetails', 'uses' => 'BillsController@billdetails']);
    Route::post('/viewbilldetails/{id}', ['as' => 'viewbilldetails', 'uses' => 'BillsController@updateBillsDetail']);
    Route::post('/viewbilldetails/items/delete/{id}', ['as' => 'deletebillitem', 'uses' => 'BillsController@deleteBillItem']);
    Route::post('/viewbilldetails/payment/delete/{id}', ['as' => 'deletebillpayment', 'uses' => 'FarmPayablePaymentController@deleteBillpayment']);
    Route::get('/createbillrecords', ['as' => 'createbills', 'uses' => 'BillsController@index']);
    Route::post('/createbillrecords', ['as' => 'createbills', 'uses' => 'BillsController@createBills']);
    Route::get('/billpayment', ['as' => 'billpayment', 'uses' => 'BillsController@index']);
    Route::post('/billpayment/{id?}', ['as' => 'billpayment', 'uses' => 'FarmPayablesController@makePayment']);

    Route::get('/items', ['as' => 'items', 'uses' => 'FarmItemsController@index']);
    Route::post('/createFarmItem', ['as' => 'createFarmItem', 'uses' => 'FarmItemsController@createFarmItem']);
    
   // Route::match(['get', 'post'], 'item/create', ['as' => 'itemcreate', 'uses' => 'FarmItemsController@createFarmItem']);
    Route::match(['get', 'post'], 'item/update/{id}', ['as' => 'itemupdate', 'uses' => 'FarmItemsController@updateFarmItem']);
    Route::delete('item/delete/{id}', ['as' => 'itemdelete', 'uses' => 'FarmItemsController@deleteFarmItem']);


    //human resource
    //employee
    Route::match(['get', 'post'], 'employee', ['as' => 'employee', 'uses' => 'EmployeeController@createEmployee']);
    Route::put('employee/{id}', ['as' => 'updateemployee', 'uses' => 'EmployeeController@updateEmployee']);
    Route::delete('employee/{id}', ['as' => 'deleteemployee', 'uses' => 'EmployeeController@deleteEmployee']);
    
    //Payroll
    Route::match(['get', 'post'], 'payroll', ['as' => 'payroll', 'uses' => 'PayrollController@createPayroll']);
    Route::put('payroll/{id}', ['as' => 'updatepayroll', 'uses' => 'PayrollController@updatePayroll']);
    Route::delete('payroll/{id}', ['as' => 'deletepayroll', 'uses' => 'PayrollController@deletePayroll']);



    Route::get('/billitems', ['as' => 'billitems', 'uses' => 'BillItemsController@index']);
   // Route::match(['get', 'post'], 'billitems/create', ['as' => 'billitemcreate', 'uses' => 'BillItemsController@createBillItem']);
    Route::post('/createBillItem', ['as' => 'createBillItem', 'uses' => 'BillItemsController@createBillItem']);
    
    Route::post('/createSaleItem', ['as' => 'createSaleItem', 'uses' => 'BillItemsController@createSaleItem']);
   
    Route::match(['get', 'post'], 'billitems/update/{id}', ['as' => 'billitemupdate', 'uses' => 'BillItemsController@updateBillItem']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\ResetPassword as ResetPasswordNotification;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array


    //  col_farm_user_id,col_farm_users_code,col_fullname,col_pin_code,col_primary_contact,farm_contact_one_intl,col_position,col_date_created,col_date_time
     */
    protected $fillable = [
        'email', 'password', 'name','created_at','updated_at','primary_contact','country_code'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sendPasswordResetNotification($token)
    {
        // Your your own implementation.
        $this->notify(new ResetPasswordNotification($token,$this->name));
    }

    public function farm_account()
	{
		return $this->belongsTo(\App\Models\FarmAccount::class, 'farm_id');
	}

	public function account_categories()
	{
		return $this->hasMany(\App\Models\AccountCategory::class, 'created_by');
	}

	public function assets()
	{
		return $this->hasMany(\App\Models\Asset::class, 'created_by');
	}

	public function broken_stock_eggs()
	{
		return $this->hasMany(\App\Models\BrokenStockEgg::class, 'created_by');
	}

	public function culling_dead_birds()
	{
		return $this->hasMany(\App\Models\CullingDeadBird::class, 'created_by');
	}

	public function customers()
	{
		return $this->hasMany(\App\Models\Customer::class, 'created_by');
	}

	public function eggs_remaining_tracks()
	{
		return $this->hasMany(\App\Models\EggsRemainingTrack::class, 'updated_by');
	}

	public function employees()
	{
		return $this->hasMany(\App\Models\Employee::class, 'created_by');
	}

	public function expenses()
	{
		return $this->hasMany(\App\Models\Expense::class, 'created_by');
	}

	public function farm_accounts()
	{
		return $this->hasMany(\App\Models\FarmAccount::class, 'created_by');
	}

	public function farm_drugs()
	{
		return $this->hasMany(\App\Models\FarmDrug::class, 'vendor_id');
	}

	public function farm_drugs_recordings()
	{
		return $this->hasMany(\App\Models\FarmDrugsRecording::class, 'created_by');
	}

	public function farm_eggs()
	{
		return $this->hasMany(\App\Models\FarmEgg::class, 'created_by');
	}

	public function farm_feeds()
	{
		return $this->hasMany(\App\Models\FarmFeed::class, 'created_by');
	}

	public function farm_feed_recordings()
	{
		return $this->hasMany(\App\Models\FarmFeedRecording::class, 'created_by');
	}

	public function farm_owings()
	{
		return $this->hasMany(\App\Models\FarmOwing::class, 'created_by');
	}

	public function farm_payables()
	{
		return $this->hasMany(\App\Models\FarmPayable::class, 'created_by');
	}

	public function farm_payments()
	{
		return $this->hasMany(\App\Models\FarmPayment::class, 'created_by');
	}

	public function farm_payrolls()
	{
		return $this->hasMany(\App\Models\FarmPayroll::class, 'updated_by');
	}

	public function farm_sales()
	{
		return $this->hasMany(\App\Models\FarmSale::class, 'created_by');
	}

	public function farm_users()
	{
		return $this->hasMany(\App\Models\FarmUser::class, 'created_by');
	}

	public function good_eggs_stocks()
	{
		return $this->hasMany(\App\Models\GoodEggsStock::class, 'created_by');
	}

	public function incomes()
	{
		return $this->hasMany(\App\Models\Income::class, 'created_by');
	}

	public function income_categories()
	{
		return $this->hasMany(\App\Models\IncomeCategory::class, 'created_by');
	}

	public function login_logs()
	{
		return $this->hasMany(\App\Models\LoginLog::class);
	}

	public function payables_categories()
	{
		return $this->hasMany(\App\Models\PayablesCategory::class, 'created_by');
	}

	public function pen_houses()
	{
		return $this->hasMany(\App\Models\PenHouse::class, 'created_by');
	}

	public function pen_house_stockings()
	{
		return $this->hasMany(\App\Models\PenHouseStocking::class, 'created_by');
	}

	public function sales_details()
	{
		return $this->hasMany(\App\Models\SalesDetail::class, 'created_by');
	}

	public function stock_trackings()
	{
		return $this->hasMany(\App\Models\StockTracking::class, 'created_by');
	}

	public function subscriptions()
	{
		return $this->hasMany(\App\Models\Subscription::class, 'updated_by');
	}

	public function subscription_payments()
	{
		return $this->hasMany(\App\Models\SubscriptionPayment::class, 'paid_by');
	}

	public function subscription_plans()
	{
		return $this->hasMany(\App\Models\SubscriptionPlan::class, 'created_by');
	}

	public function vendors()
	{
		return $this->hasMany(\App\Models\Vendor::class, 'created_by');
	}
}

resources/views/users/farm_payroll.blade.php
@extends('users/layouts.farm_payroll_master') 
@section('payroll')
<article class="content forms-page">
<div class="title-block">
    <h3 class="title"> Payoll</h3>      
</div>

        <section class="section">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-block">
                        <!-- Nav tabs -->
                        <div class="container mt-3">
                            <!-- <ul class="nav nav-tabs">
                                <li class="nav-item">
                                    <a style="text-decoration: none;" class="nav-link active" data-toggle="tab" href="#bills">Payroll</a>
                                </li>
                            </ul> -->

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div id="bills" class="container tab-pane active"><br>
                                
                                    <div class="table-responsive">
                                        <table class="payrollTable table1 table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Add<br><button class="text-right btnall" id="check_all">All</button></th>
                                                    <th>Employee Name</th> 
                                                    <th>Amount To Be Paid</th>
                                                    <th>Status</th>
                                                    <!-- <th>Action</th> -->
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><input type="checkbox" name="vehicle"></td>
                                                    <td>Kwame Asante</td>
                                                    <td>
                                                        <input type="number" class="form-control" id="" value="5000" style="width:200px;">
                                                    </td>
                                                    <td>Active</td> 
                                                </tr> 
                                                <tr>
                                                    <td><input type="checkbox" name="vehicle"></td>
                                                    <td>Kwame Asante</td>
                                                    <td><input type="number" class="form-control" id="" value="5000" style="width:200px;"> </td>
                                                    <td>Active</td> 

            <section class="section">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-block">
                                <!-- Nav tabs -->
                                <div class="container mt-3">
                                    <ul class="nav nav-tabs">
                                        <li class="nav-item">
                                            <a style="text-decoration: none;" class="nav-link active" data-toggle="tab" href="#bills">Payroll</a>
                                        </li>
                                    </ul>
            
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div id="bills" class="container tab-pane active"><br>
                                            <div class="table-responsive">
                                            <form method="POST" action="{{route('account.payroll')}}">
                                                    {{csrf_field()}}
                                                <table class="payrollTable table1 table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th>Employee Name</th> 
                                                            <th>Amount To Be Paid</th>
                                                            <th>Status</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach($employees as $employee)
                                                        <tr class="">
                                                        <td style="display: none"><input name="employeeid[]"  value="{{$employee->id}}" /></td>
                                                        <td>{{$employee->first_name}} {{$employee->last_name}}</td>
                                                        <td><input name="amount[]" type="number" class="form-control" id="" value="{{$employee->salary}}"> </td>
                                                            <td>Active</td> 
                                                            <td>
                                                                <button class="make-payment btn btn-success">
                                                                    <i class="fa fa-money"></i>
                                                                </button>
                                                        </tr>  
                                                        @endforeach
                                                    </tbody>
                                                </table>
                                                <div class="text-right">
                                                    <button class="text-right btn btn-primary" data-toggle="modal" data-target="#payment">Pay Salary</button>
                                                </div>
                                            </form>
                                            </div>
                                        </div>   
                                    </div>       
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</article>

<!-- Modal -->
<div class="modal fade" id="payment" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <p>Total Amount to be paid: </p>
                <p>You are making payment to 25 employees</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" data-dismiss="modal" data-token="{{csrf_token()}}" class="delete-customer btn btn-primary">Confirm</button>
            </div>
        </div>
    </div>
</div>
<script></script>
<script>
    $('#check_all').click(function() {
        $('input[name=vehicle]').prop('checked', true);
    });

    $('#check_all').click(function() {
        $('input[name=vehicle]').prop('checked', false);
    });

</script>

@endsection

resources/views/users/vendor.blade.php
@extends('users/layouts.vendormaster')

@section('vendor')


<article class="content forms-page">
            <div class="title-block">
            	<div class="title">
				    <button type="button" class="btn btn-primary" id="btnadd" data-toggle="modal" data-target="#addVendor">Add Creditor</button>
                    
				</div>  
                <h3 class="title"> List of credtiors</h3>

                <p class="title-description"> 

               

             </p> 
            </div>

            <section class="section">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-block">
                                <section class="example">
                                    <div class="table-responsive">
                                        <table id="dataTable" class="table table-bordered table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Date Created</th>
                                                    <th>Name </th>
                                                    <th>Contact</th>
                                                    <th>Email</th>
                                                    <!-- <th>Location</th> -->
                                                    {{-- <th>Action</th>        --}}
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($vendors as $vendor)
                                                <tr>
                                                    <td>{{\Carbon\Carbon::parse($vendor->created_at)->format('jS \o\f F, Y')}}</td>
                                                    <td>{{$vendor->name}}</td>
                                                    <td>{{$vendor->contact}}</td>
                                                    <td>{{$vendor->email}}</td>
                                                    <!-- <td>{{$vendor->location}}</td> -->

                                                    {{-- <td>
                                                         
                                                        <button class="btn btn-info">
                                                            <i class="fa fa-pencil"></i>
                                                        </button>
                                                        <button class="btn btn-danger">
                                                            <i class="fa fa-trash"></i>
                                                        </button>
                                                    </td> --}}

                                                </tr>
                                                @endforeach 
                                            </tbody>
                                        </table>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            
</article>



 <!-- ADD P MODAL -->
    <div class="modal fade" id="addVendor" tabindex="-1" role="dialog" aria-labelledby="addVendor" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <section class="section">
                <div class="col-md-12">
                    <div class="modal-header">
                        <h4 class="modal-title" id="modelTitleId">Creditor</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-content">
                        <div class="card card-block sameheight-item">
                            <form method="POST" action="{{route('account.vendor')}}">
                                {{csrf_field()}} 
                                <div class="row form-group">
                                    <div class="col-7">
                                        <div class="form-group row">
                                            <label class="col-sm-5 form-control-label">Name of Creditor <label style="color: red;">*</label></label>
                                            <div class="col-sm-7">
                                                <input required type="text" name="name" class="form-control" id="" placeholder="Creditor's name"> 
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-5">
                                        <div class="form-group row">
                                            <label {{-- for="inputEmail3" --}} class="col-sm-4 form-control-label">Contact<label style="color: red;">*</label></label>
                                            <div class="col-sm-8">
                                                <input type="number" name="contact" class="form-control" id="" placeholder="024XXXXXXXX"> 
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row form-group">
                                    <div class="col-7">
                                        <div class="form-group row">
                                            <label class="col-sm-5 form-control-label">Location<label style="color: red;">*</label></label>
                                            <div class="col-sm-7">
                                                <input required type="text"  name="location" class="form-control" id="" placeholder="Enter Creditor's location"> 
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-5">
                                        <div class="form-group row">
                                            <label class="col-sm-4 form-control-label">Email<label style="color: red;">*</label></label>
                                            <div class="col-sm-8">
                                                <input  type="text"  name="email" class="form-control" id="" placeholder="Creditor@example.com"> 
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row form-group">
                                    <div class="col-7">
                                        
                                        <div class="form-group row">
                                            <label class="col-sm-5 form-control-label">Address</label>
                                            <div class="col-sm-7">
                                                <input required type="text"  name="address" class="form-control" id="" placeholder="Enter Creditor's address"> 
                                            </div>
                                        </div>

                                    </div> 
                                </div>

                                <div class="row form-group">
                                    <div class="col-7"> 
                                       <div class="form-group row">
                                            <label class="col-sm-5 form-control-label">Country</label>
                                            <div class="col-sm-7">
                                                <input required type="text"  name="country" class="form-control" id="" placeholder="Enter Creditor's country"> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>   
                            </form>
                        </div>
                    </div>
                </div>
            </section>    
        </div>
    </div>
@endsection